### ISSUE TITLE
Warning: [JSS] Rule is not linked. Missing sheet option "link: true".

### ISSUE THREAD

**Issue by kayotimoteo** [M0kY/react-form-stepper#206]
I am using Chakra UI and getting this error. Thanks.

Warning: [JSS] Rule is not linked. Missing sheet option "link: true".

**Comment by M0kY** [comment]
Hello, this seems to be an open issue with the jss library #cssinjs/jss#1143 and not directly caused by react-form-stepper. Since it's only a warning I would suggest ignoring it for now if nothing breaks.

**Comment by RodrigoTomeES** [comment]
Hi, is there any update of this? It's very frustrating this issue, it dirties my log console in the server
