### ISSUE TITLE
how we can make the stpper clickable to go any step without on click on step

### ISSUE THREAD

**Issue by Annshuk** [M0kY/react-form-stepper#208]
is there any props to use to click on stpper to go step directly

**Comment by M0kY** [comment]
I'm not sure if I understood correctly, but hopefully what you wanted is possible with the new release `1.3.0`

**Comment by trainoasis** [comment]
a bit late to the party but am also interested in that. Clicking stepper circles would take the user to the relevant step. Did not find this in the docs, did I miss something?
