### ISSUE TITLE
Not work in React 18

### ISSUE THREAD

**Issue by igortullio** [M0kY/react-form-stepper#421]

**Comment by ladaniavadh** [comment]
Yes, you are correct. I am not able apply this style for connectors. Otherwise all are working good.
What kind of issue are you facing ?
I need help to apply style for connectors.

**Comment by igortullio** [comment]
I'm using Next with React 18. When I run it locally (npm run dev) the styles look like this:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/20797306/171037900-eacfa0dc-b403-4a33-a1ea-9e02048872fe.png">

But when I generate the build (next build && next export) everything is ok:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/20797306/171037799-e5ba11b1-4ea0-4a13-a6a3-a8b77e4e62f7.png">

**Comment by elohanlon** [comment]
I'm seeing the same problem in a create-react-app context:

Doesn't work in development (`npm run start`):

![Screen Shot 2022-05-30 at 3 04 51 PM](https://user-images.githubusercontent.com/1017323/171048579-b865da97-06b5-49f8-83ad-4a89da322e97.png)

Only shows up after a build (`npm run build && npx serve build`):

![Screen Shot 2022-05-30 at 3 04 56 PM](https://user-images.githubusercontent.com/1017323/171048594-0a2a83f4-f0d5-4976-803c-93503672b88f.png)

**Comment by M0kY** [comment]
Thanks for the feedback and sorry for the late response. It seems the issues you are facing were caused by react-jss not playing nicely with react v18. I created a new release so now it should work fine.

**Comment by elohanlon** [comment]
I just tested the new release and things look good!  Thanks, @M0kY !

**Comment by ladaniavadh** [comment]
Thanks for your effort @M0kY 👍

**Comment by igortullio** [comment]
Thanks, works now!
